### PR TITLE
update ws to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by dominicbarnes**
there are 2 advisories with the version of ws currently in use:
 - https://nodesecurity.io/advisories/67
 - https://nodesecurity.io/advisories/120

they are medium and high vulnerabilities respectively

### CODE REVIEW

**Comment by dominicbarnes** [comment]
This will fix #66 

I've already run `npm test` on Mac OSX, will run on Ubuntu Linux when I get home tonight.

**Comment by dominicbarnes** [comment]
Tests also pass on Ubuntu Linux.

**Comment by napcs** [comment]
Thank you for this. I will look at this shortly.

**Comment by dominicbarnes** [comment]
Thanks for merging! How long until this change is published to npm?

**Comment by napcs** [comment]
Soon.

**Pull request merged**
