### PR TITLE
Explicit path for websocket server

### PR DESCRIPTION
**Pull request by Mitranim**
* accept websocket connections on `/livereload` or `options.serverPath`, ignore otherwise
* this allows to use the same server instance as a proxy to another websocket server

other corrections

* use async IO to serve client script
* idempotent `server.watch`

### CODE REVIEW

**Comment by Mitranim** [comment]
Hmm seems like the CI failure is due to test dependencies rather than PR itself... but I could be wrong.

**Comment by napcs** [comment]
I think this idea has merit, but the PR changes a lot more than the description says. Can you close this and isolate the changes to separate PRs?

**Comment by napcs** [comment]
@Mitranim ping

**Comment by Mitranim** [comment]
Opps sorry, over capacity the last few days. Are you sure we should split the changes? The other stuff is pretty minor.

**Comment by napcs** [comment]
Closing due to inactivity

**Pull request closed without merging**
