### PR TITLE
Support multiple paths from the command line.

### PR DESCRIPTION
**Pull request by raineorshine**
I need the multiple-path functionality added in #31 to be available on the command line.

I am splitting the string on commas for simplicity, but if another approach is preferred that would be fine.

### CODE REVIEW

**Comment by napcs** [comment]
This looks pretty good to me. I'll run some tests on this and merge it in this week. Hopefully we can get a release out too. Thank you.

**Comment by andygrn** [comment]
Any chance of getting this merged soon?

**Comment by napcs** [comment]
@andygrn soon. I just took a new day job and have a couple other PRs to include into a new release. Planning for this week yet (I hope!)

**Comment by napcs** [comment]
@andygrn @raineorshine Published to NPM as 0.5.0

**Pull request merged**
