### PR TITLE
Added --quiet option to suppress debug errors in console for the CLI implementation

### PR DESCRIPTION
**Pull request by roikles**

### CODE REVIEW

**Comment by napcs** [comment]
@roikles What's the reasoning for suppressing the output?

**Comment by roikles** [comment]
@napcs The 'Refresh' notifications clutter up our debugging output from sass and jslint e.t.c. As I can see the browser window refresh most of the time it may not be necessary to log every browser refresh in the terminal output.

There have been situations in the past which have required some debugging of Livereload issues which is why I propose a 'quiet' flag rather than just supressing the output all together.

**Comment by napcs** [comment]
@roikles Hmmm. I can see that. 
I'm not comfortable with this PR though. I think there should be a message that shows initially that displays the polling interval and the port. I'm fine with suppressing the reloading messages though, and I'm actually thinking it would be best if those messages were OFF by default and you would need a debugging flag on by default. 

Care to convince me I'm wrong?

**Comment by roikles** [comment]
@napcs I agree that the initial message is important and I would be fine if the 'Refresh' messages are off by default I think its probably the best implementation.

I'll amend the PR so it can be tested. I'll also fix the spelling :-)

**Comment by roikles** [comment]
I have rewritten the PR based on your suggestions. Im not very familiar with coffescript so I just tried my best to rewrite the js in what to me looks like the same syntax.

Essentially this now suppresses the logs of 'Refresh: ...' and also 'Browser URL: ...'. but it doesn't affect any other essential error logs.

**Comment by roikles** [comment]
Any news on this @napcs?

**Comment by napcs** [comment]
@roikles I promise it's on the list. There are a couple other PRs that I have to merge at the same time because of Node 4.x. 

It would be super helpful if you could convert the CoffeeScript to JS though using the CoffeeScript converter. Just run

```
cake build
```
to do that.  That way we're sure everything is correct.

(I plan to convert this from CoffeeScript to JS, just not right now.

**Comment by napcs** [comment]
@roikles nevermind, I'll convert and merge it. :)

**Pull request merged**
