### PR TITLE
Adding capability to watch multiple paths

### PR DESCRIPTION
**Pull request by jaymorrow**
If the provided path is a sting the `watch` method converts it to an array.

The path array is iterated over to allow for multiple directories to be searched. Each directory has the same configuration options (although this could be updated to allow for different configs).

### CODE REVIEW

**Comment by napcs** [comment]
Can you provide a clear justification for adding this? How would most people find this useful?

**Comment by jaymorrow** [comment]
When needing to look at two different paths for reloading an application. In my scenario I'm building an express app where I have static assets in the *public* folder that need to reload the site when changed. I also have files written in Jade in a *views* folder that need to reload the app when changed. My folder structure looks like this:

app
+-- controllers
+-- models
+-- public
|    +-- css
|    +-- js
+-- routes
+-- views
|    +-- index.jade

I don't want the page reload if I change one of the node.js javascript files, so I can't attach it to the *app* level.

**Comment by napcs** [comment]
Hmmm. I see what you're doing. This was originally designed around watching the static files for changes.  I don't have time to write up a section on this in the README - could you alter your PR to include a section that explains the usage for this?

**Comment by jaymorrow** [comment]
Updated the README with an example of the multiple path usage. Let me know if there's anything else I need to change.

**Comment by napcs** [comment]
Will review this weekend. Thank you!

**Comment by mrajcok** [comment]
I have the same issue.  I would like to use this new feature.  Can you update the version and npm publish it?  (The version I got from npm doesn't have this enhancement.)

**Comment by napcs** [comment]
@mrajcok It'll be up later this week. Working out another issue in the meantime.

**Pull request merged**
