### PR TITLE
Use new fs.watch API for faster polling

### PR DESCRIPTION
**Pull request by shz**
I did a quick set of measurements and I'm seeing things update a few hundred milliseconds faster on average.

There are some downsides: http://nodejs.org/api/fs.html#fs_caveats

### CODE REVIEW

**Comment by napcs** [comment]
@shz Any additional thoughts on the downsides? Do we care about a hundred milliseconds? Is there a way to fall back to the old method?

**Comment by shz** [comment]
The benefit is pretty sweet, from what I've experienced.  Feels much better being that much closer to instant, especially when making small CSS changes.  That said, I've been thinking about this and I think I want to recant a bit.  Having issues on networked filesystems seems pretty severe, as those aren't too uncommon.

I think the way to go is probably to have the `fs.watch` approach be the default, but also support a fallback to `fs.watchFile` via a user-controlled option.  If that sounds good, I'll implement and update the PR.

**Comment by napcs** [comment]
If you have a graceful way to do that, and test it, please do!

**Comment by napcs** [comment]
bump

**Comment by napcs** [comment]
One more bump before I close this.

**Comment by shz** [comment]
Hey, sorry about the radio silence, been a bit swamped.  I've put aside some time this weekend though, hoping to have this PR finished up on Monday.

**Comment by shz** [comment]
I'm going to fire up a new PR for this, had to make significant changes and a rebase, was easiest to just use a clean slate...

**Pull request closed without merging**
